blueprint:
  custom_cards:
  - mushroom-media-player-card
  - mushroom-chips-card
  description: replaces media player card with mushroom media player card + Sonos favorites by TS
  name: Replace Mushroom Media Player Card + Sonos favorites
  type: replace-card
  version: '1.0.0'
  input:
    10_fav_entity: 
      description: Choose Sonos favorite 01 entity
      type: entity-picker
      name: Entity
    11_fav_source: 
      description: Choose Sonos favorite 01 source name
      type: text-field
      name: Source
    20_fav_entity: 
      description: Choose Sonos favorite 02 entity
      type: entity-picker
      name: Entity
    21_fav_source: 
      description: Choose Sonos favorite 02 source name
      type: text-field
      name: Source
    30_fav_entity: 
      description: Choose Sonos favorite 03 entity
      type: entity-picker
      name: Entity
    31_fav_source: 
      description: Choose Sonos favorite 03 source name
      type: text-field
      name: Source
    40_fav_entity: 
      description: Choose Sonos favorite 04 entity
      type: entity-picker
      name: Entity
    41_fav_source: 
      description: Choose Sonos favorite 04 source name
      type: text-field
      name: Source
    50_fav_entity: 
      description: Choose Sonos favorite 05 entity
      type: entity-picker
      name: Entity
    51_fav_source: 
      description: Choose Sonos favorite 05 source name
      type: text-field
      name: Source
    60_fav_entity: 
      description: Choose Sonos favorite 06 entity
      type: entity-picker
      name: Entity
    61_fav_source: 
      description: Choose Sonos favorite 06 source name
      type: text-field
      name: Source  
card:
  type: vertical-stack
  cards:
    - type: custom:mushroom-media-player-card
      use_media_info: true
      use_media_artwork: true
      entity: $replace_with_input_entity$
      name: $replace_with_input_name$
      volume_controls:
        - volume_mute
        - volume_buttons
        - volume_set
      media_controls:  
        - on_off
        - shuffle
        - previous
        - play_pause_stop
        - next
        - repeat
    - type: grid
      square: false
      cards:
        - type: custom:mushroom-entity-card
          entity: $10_fav_entity$
          name: NPO Radio 2
          fill_container: true
          hide_icon: false
          use_entity_picture: true
          primary_info: name
          secondary_info: none
          hold_action:
            action: none
          double_tap_action:
            action: none
          tap_action:
            action: call-service
            service: media_player.select_source
            service_data:
              source: $11_fav_source$
            target:
              entity_id: $replace_with_input_entity$
        - type: custom:mushroom-entity-card
          entity: $20_fav_entity$
          name: NPO 3FM
          fill_container: true
          hide_icon: false
          use_entity_picture: true
          primary_info: name
          secondary_info: none
          hold_action:
            action: none
          double_tap_action:
            action: none
          tap_action:
            action: call-service
            service: media_player.select_source
            service_data:
              source: $21_fav_source$
            target:
              entity_id: $replace_with_input_entity$
        - type: custom:mushroom-entity-card
          entity: input_boolean.dummy_radio_538_verruckte_stunden
          name: $30_fav_entity$
          fill_container: true
          hide_icon: false
          use_entity_picture: true
          primary_info: name
          secondary_info: none
          hold_action:
            action: none
          double_tap_action:
            action: none
          tap_action:
            action: call-service
            service: media_player.select_source
            service_data:
              source: $31_fav_source$
            target:
              entity_id: $replace_with_input_entity$
        - type: custom:mushroom-entity-card
          entity: $40_fav_entity$
          name: Qmusic Het Foute Uur.
          fill_container: true
          hide_icon: false
          use_entity_picture: true
          primary_info: name
          secondary_info: none
          hold_action:
            action: none
          double_tap_action:
            action: none
          tap_action:
            action: call-service
            service: media_player.select_source
            service_data:
              source: $41_fav_source$
            target:
              entity_id: $replace_with_input_entity$
        - type: custom:mushroom-entity-card
          entity: $50_fav_entity$
          name: Christmas Radio
          fill_container: true
          hide_icon: false
          use_entity_picture: true
          primary_info: name
          secondary_info: none
          hold_action:
            action: none
          double_tap_action:
            action: none
          tap_action:
            action: call-service
            service: media_player.select_source
            service_data:
              source: $51_fav_source$
            target:
              entity_id: $replace_with_input_entity$
        - type: custom:mushroom-entity-card
          entity: input_boolean.dummy_radio_sky_radio_christmas
          name: $60_fav_entity$
          fill_container: true
          hide_icon: false
          use_entity_picture: true
          primary_info: name
          secondary_info: none
          hold_action:
            action: none
          double_tap_action:
            action: none
          tap_action:
            action: call-service
            service: media_player.select_source
            service_data:
              source: $61_fav_source$
            target:
              entity_id: $replace_with_input_entity$
