blueprint:
  name: Thermostat and AC card
  description: Thermostat and AC card by TS
  version: "0.8"
  type: card
  
  custom_cards:
    - simple-thermostat
    - mushroom-template-card
    - stack-in-card

  input:
  
    01_Thermostat_name:
      name: Thermostat name
      description: Thermostat name
      type: text-field
  
    02_thermostat_entity:
      name: Thermostat entity
      description: The thermostat entity
      type: entity-picker
       
    03_thermostat_controls_buttons_hide_show:
      name: Controls hide
      description: Controls hide
      type: checkbox
      default_value: false
       
    04_thermostat_controls_names_hide_show:
      name: If Controls are activated name hide
      description: If Controls are activated name hide
      type: checkbox
      default_value: false
       
    05_thermostat_controls_icons_hide_show:
      name: If Controls are activated icon hide
      description: If Controls are activated icon hide
      type: checkbox
      default_value: false
       
    06_thermostat_controls_heading_hide_show:
      name: If Controls are activated heading hide
      description: If Controls are activated heading hide
      type: checkbox
      default_value: false
       
    07_thermostat_temperature_hide_show:
      name: Temperature hide
      description: Hide temperature
      type: checkbox
      default_value: false

    08_thermostat_state_hide_show:
      name: State hide
      description: Hide state
      type: checkbox
      default_value: false
       
    09_thermostat_sensors_label_hide_show:
      name: If sensors are activated hide label
      description: If the sensors are activated hide sensors label
      type: checkbox
      default_value: false
       
    10_room_temperature:
      name: Pick the entity for the room temperature
      description: The temperature of this entity will be used in the card
      type: entity-picker
      
    11_room_humidity:
      name: Pick the entity for the room hunidity
      description: The humidity of this entity will be used in the card
      type: entity-picker

card:
  type: horizontal-stack
  cards:
    - type: custom:stack-in-card
      cards:
        - type: custom:mushroom-template-card
          primary: $01_Thermostat_name$
          secondary: >-
            🌡{{
            state_attr('$02_thermostat_entity$','current_temperature')|float}}°C
            💧{{
            states('$11_room_humidity$')|float}}%
          icon: |-
            {% set mode = states('$02_thermostat_entity$') %}
            {% if mode == 'heat' %}
            mdi:fire
            {% elif mode == 'cool' %}
            mdi:snowflake
            {% elif mode == 'heat_cool' %}
            mdi:sun-snowflaked-
            {% elif mode == 'dry' %}
            mdi:water-percent
            {% elif mode == 'fan_only' %}
            mdi:fan
            {% else %}
            mdi:air-conditioner
            {% endif %}
          icon_color: |-
            {% set status = states('$02_thermostat_entity$') %}
            {% if status == 'cool' %}
            #2b9af9
            {% elif status == 'heat' %}
            #f92b2b
            {% elif status == 'dry' %}
            #efbd07
            {% elif status == 'heat_cool' %}
            orange
            {% elif status == 'fan_only' %}
            #00d11c
            {% else %}
            grey
            {% endif %}
          tap_action: none
        - type: custom:simple-thermostat
          entity: $02_thermostat_entity$
          header: false
          control: $03_thermostat_controls_buttons_hide_show$
          layout:
            step: column
            mode:
              names: false
              icons: true
              headings: false
            sensors:
              labels: $09_thermostat_sensors_label_hide_show$
          hide:
            temperature: true
            state: true
          decimals: '0'
          step_size: '1'
        - type: horizontal-stack
          cards:
            - type: button
              tap_action:
                action: toggle
              entity: switch.salon_streamer
              show_name: false
              show_icon: true
              show_state: false
              icon_height: 25px
              name: Streamer
            - type: button
              tap_action:
                action: toggle
              entity: input_boolean.wykres_temp1
              show_name: false
              show_icon: true
              show_state: false
              icon_height: 25px
            - type: button
              tap_action:
                action: toggle
              entity: input_boolean.wykres_wilg1
              show_name: false
              show_icon: true
              show_state: false
              icon_height: 25px
            - type: button
              tap_action:
                action: toggle
              entity: input_boolean.zuzy_energ1
              show_name: false
              show_icon: true
              show_state: false
              icon_height: 25px
        - type: custom:stack-in-card
          mode: vertical
          cards:
            - type: conditional
              conditions:
                - entity: input_boolean.wykres_temp1
                  state: 'on'
              card:
                type: statistics-graph
                entities:
                  - sensor.hmip_wth_2_000a9be9a3e3ae_actual_temperature
                title: Temperatura Salon
                stat_types:
                  - mean
                chart_type: line
                days_to_show: 3
            - type: conditional
              conditions:
                - entity: input_boolean.wykres_wilg1
                  state: 'on'
              card:
                type: statistics-graph
                entities:
                  - sensor.hmip_wth_2_000a9be9a3e3ae_humidity
                title: Wilgotność Sypialni
                stat_types:
                  - mean
                chart_type: bar
                days_to_show: 3
            - type: conditional
              conditions:
                - entity: input_boolean.zuzy_energ1
                  state: 'on'
              card:
                type: entities
                entities:
                  - entity: sensor.sypialnia_daily_cool_energy_consumption
                    name: Dzienne
                  - entity: sensor.sypialnia_daily_heat_energy_consumption
                    name: Dzienne
                  - entity: sensor.sypialnia_weekly_cool_energy_consumption
                    name: Tygodniowe
                  - entity: sensor.sypialnia_weekly_heat_energy_consumption
                    name: Tygodniowe
                  - entity: sensor.sypialnia_yearly_cool_energy_consumption
                    name: Roczne
                  - entity: sensor.sypialnia_yearly_heat_energy_consumption
                    name: Roczne
                title: Zużycie energii
                show_header_toggle: false
                state_color: false
