blueprint:
  custom_cards:
    - mushroom-climate-card
    - stack-in-card
  description: Replace Thermostat and AC card by TS
  input:
    01_Thermostat_name:
      description: Thermostat name
      name: Thermostat name
      type: text-field
    02_helper_name:
      description: Name for the helper
      name: Pick the name for the helper
      type: text-field
  name: Replace Thermostat and AC card
  type: replace-card
  version: 1.1.0
card:
  cards:
    - cards:
        - type: custom:mushroom-climate-card
          entity: climate.$02_helper_name$
          fill_container: true
          show_temperature_control: true
          hvac_modes:
            - auto
            - heat
            - cool
            - fan_only
            - heat_cool
            - dry
            - "off"
          name: $01_Thermostat_name$
        - cards:
            - type: button
              show_name: false
              show_icon: true
              name: "Fan modes"
              tap_action:
                action: more-info
              hold_action:
                action: none
              entity: input_boolean.dummy_popup_$02_helper_name$_fan
              icon_height: 24px
            - type: button
              show_name: false
              show_icon: true
              name: "Swing modes"
              tap_action:
                action: more-info
              hold_action:
                action: none
              entity: input_boolean.dummy_popup_$02_helper_name$_swing
              icon_height: 24px
            - type: button
              show_name: false
              show_icon: true
              name: "Special modes"
              tap_action:
                action: more-info
              hold_action:
                action: none
              entity: input_boolean.dummy_popup_$02_helper_name$_special
              icon_height: 24px
            - type: button
              show_name: false
              show_icon: true
              name: "Temperatures"
              tap_action:
                action: more-info
              hold_action:
                action: none
              entity: input_boolean.dummy_popup_$02_helper_name$_temp
              icon_height: 24px
            - type: button
              show_name: false
              show_icon: true
              name: "Luchtvochtigheid"
              tap_action:
                action: more-info
              hold_action:
                action: none
              entity: input_boolean.dummy_popup_$02_helper_name$_humidity
              icon_height: 24px
            - type: button
              show_name: false
              show_icon: true
              name: "Energie"
              tap_action:
                action: more-info
              hold_action:
                action: none
              entity: input_boolean.dummy_popup_$02_helper_name$_energy
              icon_height: 24px
            - type: button
              show_name: false
              show_icon: true
              name: "Schedule"
              tap_action:
                action: more-info
              hold_action:
                action: none
              entity: input_boolean.dummy_popup_$02_helper_name$_schedule
              icon_height: 24px
          type: horizontal-stack
      type: custom:stack-in-card
  type: vertical-stack
