blueprint:
  name: Replace Mini-Graph for temperature sensor
  description: Replace Mini-Graph for temperature sensor by TS
  version: "1.0.0"
  type: replace-card

  custom_cards:
    - mini-graph-card
card:
  color_thresholds:
    - color: '#0000ff'
      value: -10
    - color: '#0037ff'
      value: -5
    - color: '#006eff'
      value: 0
    - color: '#00c8ff'
      value: 5
    - color: '#00ff7b'
      value: 10
    - color: '#ffff00'
      value: 15
    - color: '#ff8000'
      value: 20
    - color: '#ff3700'
      value: 25
    - color: '#ff0000'
      value: 30
  entities:
    - entity: $replace_with_input_entity$
  hours_to_show: 72
  type: custom:mini-graph-card
